kind: pipeline
name: frontend

steps:
- name: build
  image: node:5.3.0
  commands:
  - npm install
  - npm test
- name: notify
  image: plugins/slack
  settings:
    room: general
    webhook: https://hooks.slack.com/services/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
  when:
    status:
    - failure
---
kind: pipeline
name: backend

platform:
  os: linux
  arch: amd64
  
steps:
- name: build
  image: java:openjdk-7
  commands:
    - export GRADLE_USER_HOME=~/.gradle
    - chmod +x ./gradlew
    - ./gradlew compileJava
  when:
    event:
    - push
    branch:
    - develop
- name: test
  image: java:openjdk-7
  commands:
    - export GRADLE_USER_HOME=~/.gradle
    - chmod +x ./gradlew
    - ./gradlew test
  when:
    event:
    - push
    branch:
    - develop
- name: code coverage
  image: java:openjdk-7
  commands:
    - export GRADLE_USER_HOME=~/.gradle
    - chmod +x ./gradlew
    - ./gradlew jacocoTestReport
    - ./gradlew jacocoTestCoverageVerification
  when:
    event:
    - push
    branch:
    - develop
- name: detached_step
  image: node
  detach: true
  commands:
  - df -h
- name: notify
  image: plugins/slack
  settings:
    room: general
    webhook: https://hooks.slack.com/services/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
  when:
    status: [ success, failure ]
trigger:
  branch:
  - develop
  event:
  - push
services:
- name: database
  image: mysql
  entrypoint: [ mysqld ]
