kind: pipeline
name: frontend

steps:
- name: build
  image: node:8.6.0
  commands:
  - npm install
  - npm run build
---
kind: pipeline
name: backend

platform:
  os: linux
  arch: amd64
  
steps:
- name: build
  image: java:openjdk-7
  commands:
    - export GRADLE_USER_HOME=~/.gradle
    - chmod +x ./gradlew
    - ./gradlew test
  when:
    event:
    - push
    branch:
    - master
    - develop
- name: static_code_analysis
  image: govindarajanv/my-docker-whale:latest  
- name: detached_steps
  image: node
  detach: true
  commands:
  - df -h
trigger:
  branch:
  - master
  event:
  - push
services:
- name: database
  image: mysql
  entrypoint: [ mysqld ]
---
kind: pipeline
name: Notification

steps:
- name: notification
  image: plugins/slack
  settings:
    room: general
    webhook: https://hooks.slack.com/services/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

depends_on:
- frontend
- backend
trigger:
  branch:
  - master

  status:
  - success
  - failure
