- &notify_on_failure
    image: plugins/slack
    settings:
      room: general
      webhook: https://hooks.slack.com/services/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
    when:
      status:
      - failure
kind: pipeline
name: frontend

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
- name: notify
  image: plugins/slack
  settings:
    room: general
    webhook: https://hooks.slack.com/services/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
  when:
    status:
    - failure
---
kind: pipeline
name: backend

platform:
  os: linux
  arch: amd64
  
steps:
- name: build
  image: java:openjdk-7
  commands:
    - export GRADLE_USER_HOME=~/.gradle
    - chmod +x ./gradlew
    - ./gradlew test
  when:
    event:
    - push
    branch:
    - feature
- name: detached_steps
  image: node
  detach: true
  commands:
  - df -h
- name: notify
  image: plugins/slack
  settings:
    room: general
    webhook: https://hooks.slack.com/services/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
  when:
    status:
    - failure
trigger:
  branch:
  - feature
  event:
  - push
services:
- name: database
  image: mysql
  entrypoint: [ mysqld ]
