kind: pipeline
name: default

platform:
  os: linux
  arch: arm
  
steps:
- name: build
  image: java:openjdk-7
  commands:
    - export GRADLE_USER_HOME=~/.gradle
    - chmod +x ./gradlew
    - ./gradlew test
  when:
    event:
    - push
    branch:
    - master
