kind: pipeline
name: default

platform:
  os: linux
  arch: amd64
  
steps:
- name: build
  image: java:openjdk-7
  commands:
    - export GRADLE_USER_HOME=~/.gradle
    - chmod +x ./gradlew
    - ./gradlew test
  when:
    event:
    - push
    branch:
    - master
- name: test
  image: plugins/docker
  settings:
    repo: octocat/hello-world
    tags: latest
    username:
      from_secret: username
    password:
      from_secret: password
- name: detached_commands
  image: node
  detach: true
  commands:
  - df -h
- name: notify
  image: plugins/slack
  settings:
    room: general
    webhook: https://hooks.slack.com/services/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
services:
- name: database
  image: mysql
  entrypoint: [ mysqld ]
