kind: pipeline
name: default

steps:
- name: build
  image: java:openjdk-7
  commands:
    - export GRADLE_USER_HOME=~/.gradle
    - chmod +x ./gradlew
    - ./gradlew test
  when:
    branch:
    - master
